### ISSUE TITLE
java.util.MissingFormatArgumentException

### ISSUE THREAD

**Issue by dmitrikudrenko** [personaly/Android-SDK#1]
I called PersonaSdk.initNoId(getApplicationContext(), applicationHash) and got that error

Caused by: java.util.MissingFormatArgumentException: Format specifier: s
            at java.util.Formatter.getArgument(Formatter.java:1111)
            at java.util.Formatter.doFormat(Formatter.java:1076)
            at java.util.Formatter.format(Formatter.java:1042)
            at java.util.Formatter.format(Formatter.java:1011)
            at java.lang.String.format(String.java:1554)
            at java.lang.String.format(String.java:1528)
            at ly.persona.sdk.PersonaSdk.initNoId(PersonaSdk.java:101)

**Comment by bhavikmehta5491** [comment]
Me too getting the same issue
